from sqlalchemy import Boolean, Column, DateTime, Integer, String, Text, DECIMAL
from lotus_dashboard.database import Base


class LeadInsight(Base):
    __tablename__ = "lead_insight"

    id = Column(Integer, primary_key=True)
    lead_id = Column(Integer, index=True)
    deal_id = Column(Integer, index=True)
    state = Column(Integer, index=True)
    lead_sender = Column(String(255), index=True)
    category = Column(String(255), index=True)
    store_format = Column(String(255), index=True)
    source = Column(String(255), index=True)
    brand_type = Column(String(255), index=True)
    rent_type = Column(String(255), index=True)
    size_range = Column(String(255), index=True)
    lead_created_at = Column(DateTime, index=True)
    deal_created_at = Column(DateTime, index=True)
    type = Column(String(255), index=True)
    mall_id = Column(Integer, index=True)
    area_province = Column(String(255), index=True)
    mall_name = Column(String(255), index=True)
    mall_province = Column(String(255), index=True)
    mall_type = Column(String(255), index=True)
    mall_region = Column(String(255), index=True)
    mall_district = Column(String(255), index=True)
    province = Column(String(255), index=True)
    lead_created_day_of_week = Column(String(255), index=True)
    bin_size_range = Column(String(255), index=True)
    deal_task_id = Column(Integer, index=True)
    task_id = Column(Integer, index=True)
    status = Column(String(255), index=True)
    task_status = Column(String(255), index=True)
    deal_task_due_date = Column(String(255), index=True)
    is_expired = Column(Boolean, index=True)
    comment_id = Column(Integer, index=True)
    user_id = Column(Integer, index=True)
    text = Column(Text)
    comment_status = Column(String(255), index=True)
    loi_reference = Column(String(255), index=True)
    comment_created_at = Column(DateTime, index=True)
    deal_status_label = Column(String(255), index=True)
    deal_time_used = Column(DECIMAL(10, 6), index=True)
    first_contacted_time_used = Column(DECIMAL(10, 6), index=True)
    contacted_time_used = Column(DECIMAL(10, 6), index=True)
